### ISSUE TITLE
PHP-Function: bug with 1 php file and multi functions

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wgblocks#10]
Hi,
I cant use 1 php file with multi function
example:

toto.php
content:

```
<?php

// Affiche toutes les informations, comme le ferait INFO_ALL

function totophpinfo()
{
	phpinfo();
}
  
// Affiche uniquement le module d'information.
// phpinfo(8) fournirait les mêmes informations.
function tutuphpinfo()
{
	phpinfo(INFO_MODULES);
}  
```

item 1:
PHP-Function / full phpinfo / toto.php / totophpinfo

All is ok, it works !
Then I add a new item:

Item 2: 
PHP-Function / phpinfo modules / toto.php / tutuphpinfo

> Fatal error: Cannot redeclare totophpinfo() (previously declared in \uploads\wgblocks\functions\toto.php:5) in upload\wgblocks\functions\toto.php on line 5

**Comment by ggoffy** [comment]
hi. this is a simple module, please split your different functions to different files

**Comment by alain01** [comment]
ok no problem but give this information on "help":
1 file = 1 function

**Comment by ggoffy** [comment]
help file adapted

**Comment by ggoffy** [comment]
hi Alain. as I had the same problem I solved it with https://github.com/XoopsModules25x/wgblocks/pull/14
